export const PRODUCTS = [
  {
    id: "knowledge",
    name: "AI 智库机器人",
    en: "Knowledge Bot",
    tagline: "机务手册秒级检索",
    desc: "面向机务维修人员查阅技术手册、工卡、维修方案耗时长且跨系统信息分散的痛点,基于开源 LLM + RAG 本地化部署,完成专家知识结构化梳理与向量知识库搭建,设计对话流程提升一线工作效率。",
    color: "from-cyan-500 to-blue-600",
    glow: "shadow-glow-cyan",
    icon: "Bot",
    pain: "维修工查阅技术手册平均耗时 15-30 分钟,跨 AMM/工卡/MEL 多系统,信息分散、版本不一致。",
    metrics: [
      { label: "检索响应", value: "< 2s" },
      { label: "工卡匹配", value: "92%" },
      { label: "覆盖手册", value: "200+" },
    ],
    stack: ["ChromaDB", "BGE-zh", "GLM-4-Flash", "FastAPI"],
  },
  {
    id: "marketing",
    name: "AI 营销内容生成器",
    en: "Content Studio",
    tagline: "品牌一致的多平台素材",
    desc: "面向营销日常素材产出慢、风格一致性难保证的问题。基于月度用量测算成本,确定 MVP 阶段调用成熟 API 的方案,和运营协作定义多模态内容模板与品牌风格约束,以内容采纳率为北极星指标,根据未采纳案例反向优化。",
    color: "from-pink-500 to-purple-600",
    glow: "shadow-glow-purple",
    icon: "Pen",
    pain: "营销日常出 30+ 素材,跨平台风格难统一,法务/品牌审核返工率高,一次通过率不足 50%。",
    metrics: [
      { label: "一次通过率", value: "78%" },
      { label: "单条耗时", value: "10s" },
      { label: "采纳率", value: "↑ 35%" },
    ],
    stack: ["GLM-4-Flash", "Style Rules", "Few-shot"],
  },
  {
    id: "analytics",
    name: "AI 生产分析助手",
    en: "NL2SQL Analyst",
    tagline: "自然语言直达数据",
    desc: "针对管理者日常查询需求依赖人工拉取多系统数据、固定报表无法覆盖突发分析的问题。协同数据团队梳理多系统数据源,设计 NL2SQL 自然语言查询方案,并定期分析查询日志,将高频查询固化为报表。",
    color: "from-emerald-500 to-teal-600",
    glow: "shadow-glow-brand",
    icon: "BarChart3",
    pain: "管理者 80% 的临时数据需求走人工提单,平均响应 4-8 小时,排产决策滞后。",
    metrics: [
      { label: "查询响应", value: "< 3s" },
      { label: "SQL 准确率", value: "85%" },
      { label: "高频固化", value: "12 张" },
    ],
    stack: ["GLM-4-Flash", "SQLite", "Few-shot SQL", "SQL Guard"],
  },
  {
    id: "forecast",
    name: "AI 供应链需求预测",
    en: "Demand Forecast",
    tagline: "XGBoost 时序预测",
    desc: "面向航材消耗预测依赖历史经验及过度备库成本难以平衡的场景。采用 XGBoost 构建时序预测模型,硬件复用现有服务器,提供业务假设作为特征输入,定义分场景评价标准,迭代优化特征权重与超参数。",
    color: "from-orange-500 to-red-600",
    glow: "shadow-glow-brand",
    icon: "TrendingUp",
    pain: "航材备库成本与缺料风险难以平衡,过度备库年成本超千万,缺料导致 AOG 风险。",
    metrics: [
      { label: "MAPE", value: "8.2%" },
      { label: "库存周转", value: "↓ 18%" },
      { label: "AOG 次数", value: "→ 0" },
    ],
    stack: ["XGBoost", "Pandas", "Joblib", "SQLite"],
  },
] as const;

export type ProductId = (typeof PRODUCTS)[number]["id"];
